### ISSUE TITLE
Some properties are no longer correct

### ISSUE THREAD

**Issue by BerendWouters** [Brixel/SpaceAPI#31]
- Logo is referring to the wiki. The wiki no longer exists.
- Both IRC (`irc`) and the mailing list (`ml`) are no longer in use.

**Comment by Steamrunner** [comment]
After this update the api is no longer valid. 
https://spaceapi.io/validator/

**Comment by BerendWouters** [comment]
Nice catch, I'll update the json serializer to ignore null values.

**Comment by BerendWouters** [comment]
The issue has been resolved, the JSON is valid again. Thanks @Steamrunner for bringing it to my attention.

**Comment by Steamrunner** [comment]
confirmed fixed!
